<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>Brainvest.Dscribe.Metadata</AssemblyName>
    <RootNamespace>Brainvest.Dscribe.Metadata</RootNamespace>
  </PropertyGroup>

	<Import Project="..\..\SolutionInfo.xml" />

	<PropertyGroup>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <WarningsAsErrors />
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Infrastructure\Abstractions\Abstractions.csproj" />
    <ProjectReference Include="..\MetadataDbAccess\MetadataDbAccess.csproj" />
  </ItemGroup>

</Project>
