// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Migrations_Runtime_PostgreSql;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Migrations_Runtime_PostgreSql.Migrations
{
    [DbContext(typeof(MetadataDbContext_PostgreSql))]
    [Migration("20200428155721_AdditionalBehaviors")]
    partial class AdditionalBehaviors
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Brainvest.Dscribe.MetadataDbAccess.Entities.AdditionalBehavior", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Definition")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("AdditionalBehaviors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "DisplayAsDate"
                        },
                        new
                        {
                            Id = 2,
                            Name = "DisplayAsDateTime"
                        },
                        new
                        {
                            Id = 3,
                            Name = "SetTimeOnInsert"
                        },
                        new
                        {
                            Id = 4,
                            Name = "SetTimeOnUpdate"
                        },
                        new
                        {
                            Id = 5,
                            Name = "ShowDatePicker"
                        },
                        new
                        {
                            Id = 6,
                            Name = "ShowDateTimePicker"
                        });
                });

            modelBuilder.Entity("Brainvest.Dscribe.MetadataDbAccess.Entities.AppInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("AppTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("DataConnectionString")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DatabaseProviderId")
                        .HasColumnType("integer");

                    b.Property<string>("DbContextName")
                        .HasColumnType("text");

                    b.Property<string>("GeneratedCodeNamespace")
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsProduction")
                        .HasColumnType("boolean");

                    b.Property<string>("LobConnectionString")
                        .HasColumnType("text");

                    b.Property<int?>("MetadataReleaseId")
                        .HasColumnType("integer");

                    b.Property<bool>("MigrateDatabase")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.Property<int?>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.Property<bool>("UseUnreleasedMetadata")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("AppTypeId");

                    b.HasIndex("DatabaseProviderId");

                    b.HasIndex("MetadataReleaseId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("AppInstances");
                });

            modelBuilder.Entity("Brainvest.Dscribe.MetadataDbAccess.Entities.AppType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("AppTypes");
                });

            modelBuilder.Entity("Brainvest.Dscribe.MetadataDbAccess.Entities.DataType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("ClrType")
                        .HasColumnType("text");

                    b.Property<string>("Identifier")
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.Property<bool>("IsValueType")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.ToTable("DataTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClrType = "System.Int32",
                            Identifier = "int",
                            IsValueType = true,
                            Name = "Integer"
                        },
                        new
                        {
                            Id = 2,
                            ClrType = "System.String",
                            Identifier = "string",
                            IsValueType = false,
                            Name = "String"
                        },
                        new
                        {
                            Id = 3,
                            ClrType = "System.Boolean",
                            Identifier = "bool",
                            IsValueType = true,
                            Name = "Boolean"
                        },
                        new
                        {
                            Id = 4,
                            ClrType = "System.DateTime",
                            Identifier = "Date",
                            IsValueType = true,
                            Name = "Date"
                        },
                        new
                        {
                            Id = 5,
                            ClrType = "System.TimeSpan",
                            Identifier = "Time",
                            IsValueType = true,
                            Name = "Time Of Day"
                        },
                        new
                        {
                            Id = 6,
                            ClrType = "System.DateTime",
                            Identifier = "DateTime",
                            IsValueType = true,
                            Name = "Date and Time"
                        },
                        new
                        {
                            Id = 7,
                            Identifier = "ForeignKey",
                            IsValueType = true,
                            Name = "Foreign Key"
                        },
                        new
                        {
                            Id = 8,
                            Identifier = "NavigationEntity",
                            IsValueType = false,
                            Name = "Navigation Property"
                        },
                        new
                        {
                            Id = 9,
                            Identifier = "Enum",
                            IsValueType = true,
                            Name = "Enum"
                        },
                        new
                        {
                            Id = 10,
                            Identifier = "NavigationList",
                            IsValueType = false,
                            Name = "Navigation List"
                        },
                        new
                        {
                            Id = 11,
                            ClrType = "System.Guid",
                            Identifier = "Guid",
                            IsValueType = true,
                            Name = "Guid"
                        },
                        new
                        {
                            Id = 12,
                            ClrType = "System.Decimal",
                            Identifier = "decimal",
                            IsValueType = true,
                            Name = "Decimal"
                        },
                        new
                        {
                            Id = 13,
                            ClrType = "System.Int64",
                            Identifier = "long",
                            IsValueType = true,
                            Name = "Long Integer"
                        },
                        new
                        {
                            Id = 14,
                            ClrType = "System.Int16",
                            Identifier = "short",
                            IsValueType = true,
                            Name = "Short Integer"
                        },
                        new
                        {
                            Id = 15,
                            ClrType = "System.Byte",
                            Identifier = "byte",
                            IsValueType = true,
                            Name = "Tiny Integer"
                        },
                        new
                        {
                            Id = 16,
                            ClrType = "System.Double",
                            Identifier = "double",
                            IsValueType = true,
                            Name = "Double"
                        });
                });

            modelBuilder.Entity("Brainvest.Dscribe.MetadataDbAccess.Entities.DatabaseProvider", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DatabaseProviders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "MySql"
                        },
                        new
                        {
                            Id = 2,
                            Name = "SqlServer"
                        },
                        new
                        {
                            Id = 3,
                            Name = "PostgreSql"
                        });
                });

            modelBuilder.Entity("Brainvest.Dscribe.MetadataDbAccess.Entities.EntityActionType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("EntityActionTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "GetMetadata"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Select"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Insert"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Delete"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Update"
                        },
                        new
                        {
                            Id = 6,
                            Name = "ManageMetadata"
                        },
                        new
                        {
                            Id = 7,
                            Name = "CustomNamedAction"
                        });
                });

            modelBuilder.Entity("Brainvest.Dscribe.MetadataDbAccess.Entities.EntityType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("AppTypeId")
                        .HasColumnType("integer");

                    b.Property<int?>("BaseEntityTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("CodePath")
                        .HasColumnType("text");

                    b.Property<string>("DisplayNamePath")
                        .HasColumnType("text");

                    b.Property<int>("GeneralUsageCategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.Property<string>("PluralTitle")
                        .HasColumnType("text");

                    b.Property<string>("SchemaName")
                        .HasColumnType("text");

                    b.Property<string>("SingularTitle")
                        .HasColumnType("text");

                    b.Property<string>("TableName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BaseEntityTypeId");

                    b.HasIndex("GeneralUsageCategoryId");

                    b.HasIndex("AppTypeId", "Name")
                        .IsUnique();

                    b.ToTable("EntityTypes");
                });

            modelBuilder.Entity("Brainvest.Dscribe.MetadataDbAccess.Entities.EntityTypeFacetDefaultValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("AppInstanceId")
                        .HasColumnType("integer");

                    b.Property<int?>("AppTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("DefaultValue")
                        .HasColumnType("text");

                    b.Property<int>("FacetDefinitionId")
                        .HasColumnType("integer");

                    b.Property<int>("GeneralUsageCategoryId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AppInstanceId");

                    b.HasIndex("AppTypeId");

                    b.HasIndex("FacetDefinitionId");

                    b.HasIndex("GeneralUsageCategoryId");

                    b.ToTable("EntityTypeFacetDefaultValues");
                });

            modelBuilder.Entity("Brainvest.Dscribe.MetadataDbAccess.Entities.EntityTypeFacetDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("EnumTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("FacetTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EnumTypeId");

                    b.HasIndex("FacetTypeId");

                    b.ToTable("EntityTypeFacetDefinitions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FacetTypeId = 1,
                            Name = "NotMapped"
                        });
                });

            modelBuilder.Entity("Brainvest.Dscribe.MetadataDbAccess.Entities.EntityTypeFacetValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("EntityTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("FacetDefinitionId")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EntityTypeId");

                    b.HasIndex("FacetDefinitionId");

                    b.ToTable("EntityTypeFacetValues");
                });

            modelBuilder.Entity("Brainvest.Dscribe.MetadataDbAccess.Entities.EntityTypeGeneralUsageCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("EntityTypeGeneralUsageCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "WorkingData"
                        },
                        new
                        {
                            Id = 2,
                            Name = "BasicInfo"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Model"
                        });
                });

            modelBuilder.Entity("Brainvest.Dscribe.MetadataDbAccess.Entities.EnumType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Identifier")
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("EnumTypes");
                });

            modelBuilder.Entity("Brainvest.Dscribe.MetadataDbAccess.Entities.EnumValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("EnumTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Identifier")
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EnumTypeId");

                    b.ToTable("EnumValues");
                });

            modelBuilder.Entity("Brainvest.Dscribe.MetadataDbAccess.Entities.ExpressionBody", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Body")
                        .HasColumnType("text");

                    b.Property<string>("Comments")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("DefinitionId")
                        .HasColumnType("integer");

                    b.Property<int>("FormatId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("InvalidationTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("DefinitionId");

                    b.HasIndex("FormatId");

                    b.ToTable("ExpressionBodies");
                });

            modelBuilder.Entity("Brainvest.Dscribe.MetadataDbAccess.Entities.ExpressionDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("ActiveBodyId")
                        .HasColumnType("integer");

                    b.Property<int>("AppTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.Property<string>("LongDescription")
                        .HasColumnType("text");

                    b.Property<int>("MainInputEntityTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ActiveBodyId");

                    b.HasIndex("MainInputEntityTypeId");

                    b.HasIndex("AppTypeId", "Identifier")
                        .IsUnique();

                    b.ToTable("ExpressionDefinitions");
                });

            modelBuilder.Entity("Brainvest.Dscribe.MetadataDbAccess.Entities.ExpressionFormat", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Identifier")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ExpressionFormats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Identifier = "SimplePath",
                            Title = "Simple Path"
                        },
                        new
                        {
                            Id = 2,
                            Identifier = "Json",
                            Title = "Json"
                        },
                        new
                        {
                            Id = 3,
                            Identifier = "C#",
                            Title = "C#"
                        });
                });

            modelBuilder.Entity("Brainvest.Dscribe.MetadataDbAccess.Entities.FacetType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Identifier")
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FacetTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Identifier = "bool",
                            Name = "Boolean"
                        },
                        new
                        {
                            Id = 2,
                            Identifier = "int",
                            Name = "Integer"
                        },
                        new
                        {
                            Id = 3,
                            Identifier = "string",
                            Name = "String"
                        });
                });

            modelBuilder.Entity("Brainvest.Dscribe.MetadataDbAccess.Entities.MetadataRelease", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("AppTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<byte[]>("MetadataSnapshot")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTime>("ReleaseTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Version")
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.Property<int?>("VersionCode")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AppTypeId");

                    b.ToTable("MetadataReleases");
                });

            modelBuilder.Entity("Brainvest.Dscribe.MetadataDbAccess.Entities.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("DataEntityTypeId")
                        .HasColumnType("integer");

                    b.Property<int?>("DataTypeId")
                        .HasColumnType("integer");

                    b.Property<int?>("ExpressionDefinitionId")
                        .HasColumnType("integer");

                    b.Property<int?>("ForeignKeyPropertyId")
                        .HasColumnType("integer");

                    b.Property<int>("GeneralUsageCategoryId")
                        .HasColumnType("integer");

                    b.Property<int?>("InversePropertyId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsExpression")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsNullable")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.Property<int>("OwnerEntityTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DataEntityTypeId");

                    b.HasIndex("DataTypeId");

                    b.HasIndex("ExpressionDefinitionId");

                    b.HasIndex("ForeignKeyPropertyId");

                    b.HasIndex("GeneralUsageCategoryId");

                    b.HasIndex("InversePropertyId");

                    b.HasIndex("OwnerEntityTypeId", "Name")
                        .IsUnique();

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("Brainvest.Dscribe.MetadataDbAccess.Entities.PropertyBehavior", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("AdditionalBehaviorId")
                        .HasColumnType("integer");

                    b.Property<string>("Parameters")
                        .HasColumnType("text");

                    b.Property<int>("PropertyId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AdditionalBehaviorId");

                    b.HasIndex("PropertyId");

                    b.ToTable("PropertyBehaviors");
                });

            modelBuilder.Entity("Brainvest.Dscribe.MetadataDbAccess.Entities.PropertyFacetDefaultValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("AppInstanceId")
                        .HasColumnType("integer");

                    b.Property<int?>("AppTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("DefaultValue")
                        .HasColumnType("text");

                    b.Property<int>("FacetDefinitionId")
                        .HasColumnType("integer");

                    b.Property<int>("GeneralUsageCategoryId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AppInstanceId");

                    b.HasIndex("AppTypeId");

                    b.HasIndex("FacetDefinitionId");

                    b.HasIndex("GeneralUsageCategoryId");

                    b.ToTable("PropertyFacetDefaultValues");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DefaultValue = "false",
                            FacetDefinitionId = 1,
                            GeneralUsageCategoryId = 1
                        },
                        new
                        {
                            Id = 2,
                            DefaultValue = "true",
                            FacetDefinitionId = 1,
                            GeneralUsageCategoryId = 2
                        },
                        new
                        {
                            Id = 3,
                            DefaultValue = "false",
                            FacetDefinitionId = 2,
                            GeneralUsageCategoryId = 1
                        },
                        new
                        {
                            Id = 4,
                            DefaultValue = "true",
                            FacetDefinitionId = 2,
                            GeneralUsageCategoryId = 2
                        },
                        new
                        {
                            Id = 5,
                            DefaultValue = "false",
                            FacetDefinitionId = 3,
                            GeneralUsageCategoryId = 2
                        },
                        new
                        {
                            Id = 6,
                            DefaultValue = "true",
                            FacetDefinitionId = 4,
                            GeneralUsageCategoryId = 2
                        },
                        new
                        {
                            Id = 7,
                            DefaultValue = "true",
                            FacetDefinitionId = 5,
                            GeneralUsageCategoryId = 2
                        },
                        new
                        {
                            Id = 8,
                            DefaultValue = "true",
                            FacetDefinitionId = 4,
                            GeneralUsageCategoryId = 5
                        },
                        new
                        {
                            Id = 9,
                            DefaultValue = "true",
                            FacetDefinitionId = 4,
                            GeneralUsageCategoryId = 4
                        },
                        new
                        {
                            Id = 10,
                            DefaultValue = "false",
                            FacetDefinitionId = 3,
                            GeneralUsageCategoryId = 4
                        },
                        new
                        {
                            Id = 11,
                            DefaultValue = "false",
                            FacetDefinitionId = 3,
                            GeneralUsageCategoryId = 5
                        },
                        new
                        {
                            Id = 12,
                            DefaultValue = "true",
                            FacetDefinitionId = 1,
                            GeneralUsageCategoryId = 5
                        },
                        new
                        {
                            Id = 13,
                            DefaultValue = "true",
                            FacetDefinitionId = 2,
                            GeneralUsageCategoryId = 5
                        },
                        new
                        {
                            Id = 14,
                            DefaultValue = "true",
                            FacetDefinitionId = 1,
                            GeneralUsageCategoryId = 4
                        },
                        new
                        {
                            Id = 15,
                            DefaultValue = "true",
                            FacetDefinitionId = 2,
                            GeneralUsageCategoryId = 4
                        });
                });

            modelBuilder.Entity("Brainvest.Dscribe.MetadataDbAccess.Entities.PropertyFacetDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("EnumTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("FacetTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EnumTypeId");

                    b.HasIndex("FacetTypeId");

                    b.ToTable("PropertyFacetDefinitions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FacetTypeId = 1,
                            Name = "HideInInsert"
                        },
                        new
                        {
                            Id = 2,
                            FacetTypeId = 1,
                            Name = "HideInEdit"
                        },
                        new
                        {
                            Id = 3,
                            FacetTypeId = 1,
                            Name = "IsRequired"
                        },
                        new
                        {
                            Id = 4,
                            FacetTypeId = 1,
                            Name = "HideInList"
                        },
                        new
                        {
                            Id = 5,
                            FacetTypeId = 1,
                            Name = "ReadOnlyInEdit"
                        });
                });

            modelBuilder.Entity("Brainvest.Dscribe.MetadataDbAccess.Entities.PropertyFacetValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("FacetDefinitionId")
                        .HasColumnType("integer");

                    b.Property<int>("PropertyId")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FacetDefinitionId");

                    b.HasIndex("PropertyId");

                    b.ToTable("PropertyFacetValues");
                });

            modelBuilder.Entity("Brainvest.Dscribe.MetadataDbAccess.Entities.PropertyGeneralUsageCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PropertyGeneralUsageCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "NormalData"
                        },
                        new
                        {
                            Id = 2,
                            Name = "PrimaryKey"
                        },
                        new
                        {
                            Id = 3,
                            Name = "ForeignKey"
                        },
                        new
                        {
                            Id = 4,
                            Name = "NavigationProperty"
                        },
                        new
                        {
                            Id = 5,
                            Name = "NavigationList"
                        });
                });

            modelBuilder.Entity("Brainvest.Dscribe.MetadataDbAccess.Entities.Reporting.ReportDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<byte[]>("Definition")
                        .HasColumnType("bytea");

                    b.Property<string>("DefinitionUrl")
                        .HasColumnType("text");

                    b.Property<int>("EntityTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("ReportFormatId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EntityTypeId");

                    b.HasIndex("ReportFormatId");

                    b.ToTable("ReportDefinitions");
                });

            modelBuilder.Entity("Brainvest.Dscribe.MetadataDbAccess.Entities.Reporting.ReportFormat", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ReportFormats");
                });

            modelBuilder.Entity("Brainvest.Dscribe.MetadataDbAccess.Entities.SavedFilter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("InputEntityTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InputEntityTypeId");

                    b.ToTable("SavedFilters");
                });

            modelBuilder.Entity("Brainvest.Dscribe.MetadataDbAccess.Entities.Security.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ActionName")
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("ActionTypeId")
                        .HasColumnType("integer");

                    b.Property<int?>("AppInstanceId")
                        .HasColumnType("integer");

                    b.Property<int?>("EntityTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("PermissionType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ActionTypeId");

                    b.HasIndex("AppInstanceId");

                    b.HasIndex("EntityTypeId");

                    b.HasIndex("RoleId");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PermissionType = 1,
                            RoleId = new Guid("7555dd25-ee7f-4a21-9156-3867dcbced77")
                        });
                });

            modelBuilder.Entity("Brainvest.Dscribe.MetadataDbAccess.Entities.Security.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2e17424d-9a7c-44ee-962e-0a0e12176cff"),
                            Name = "Anonymous"
                        },
                        new
                        {
                            Id = new Guid("7555dd25-ee7f-4a21-9156-3867dcbced77"),
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("Brainvest.Dscribe.MetadataDbAccess.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("ExternalUserId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("UnifiedExternalUserId")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Brainvest.Dscribe.MetadataDbAccess.Entities.AppInstance", b =>
                {
                    b.HasOne("Brainvest.Dscribe.MetadataDbAccess.Entities.AppType", "AppType")
                        .WithMany()
                        .HasForeignKey("AppTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Brainvest.Dscribe.MetadataDbAccess.Entities.DatabaseProvider", "DatabaseProvider")
                        .WithMany()
                        .HasForeignKey("DatabaseProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Brainvest.Dscribe.MetadataDbAccess.Entities.MetadataRelease", "MetadataRelease")
                        .WithMany()
                        .HasForeignKey("MetadataReleaseId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Brainvest.Dscribe.MetadataDbAccess.Entities.EntityType", b =>
                {
                    b.HasOne("Brainvest.Dscribe.MetadataDbAccess.Entities.AppType", "AppType")
                        .WithMany()
                        .HasForeignKey("AppTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Brainvest.Dscribe.MetadataDbAccess.Entities.EntityType", "BaseEntityType")
                        .WithMany()
                        .HasForeignKey("BaseEntityTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Brainvest.Dscribe.MetadataDbAccess.Entities.EntityTypeGeneralUsageCategory", "GeneralUsageCategory")
                        .WithMany()
                        .HasForeignKey("GeneralUsageCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Brainvest.Dscribe.MetadataDbAccess.Entities.EntityTypeFacetDefaultValue", b =>
                {
                    b.HasOne("Brainvest.Dscribe.MetadataDbAccess.Entities.AppInstance", "AppInstance")
                        .WithMany()
                        .HasForeignKey("AppInstanceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Brainvest.Dscribe.MetadataDbAccess.Entities.AppType", "AppType")
                        .WithMany()
                        .HasForeignKey("AppTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Brainvest.Dscribe.MetadataDbAccess.Entities.EntityTypeFacetDefinition", "FacetDefinition")
                        .WithMany()
                        .HasForeignKey("FacetDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Brainvest.Dscribe.MetadataDbAccess.Entities.EntityTypeGeneralUsageCategory", "GeneralUsageCategory")
                        .WithMany()
                        .HasForeignKey("GeneralUsageCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Brainvest.Dscribe.MetadataDbAccess.Entities.EntityTypeFacetDefinition", b =>
                {
                    b.HasOne("Brainvest.Dscribe.MetadataDbAccess.Entities.EnumType", "EnumType")
                        .WithMany()
                        .HasForeignKey("EnumTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Brainvest.Dscribe.MetadataDbAccess.Entities.FacetType", "FacetType")
                        .WithMany()
                        .HasForeignKey("FacetTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Brainvest.Dscribe.MetadataDbAccess.Entities.EntityTypeFacetValue", b =>
                {
                    b.HasOne("Brainvest.Dscribe.MetadataDbAccess.Entities.EntityType", "EntityType")
                        .WithMany("FacetValues")
                        .HasForeignKey("EntityTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Brainvest.Dscribe.MetadataDbAccess.Entities.EntityTypeFacetDefinition", "FacetDefinition")
                        .WithMany()
                        .HasForeignKey("FacetDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Brainvest.Dscribe.MetadataDbAccess.Entities.EnumValue", b =>
                {
                    b.HasOne("Brainvest.Dscribe.MetadataDbAccess.Entities.EnumType", "EnumType")
                        .WithMany("Values")
                        .HasForeignKey("EnumTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Brainvest.Dscribe.MetadataDbAccess.Entities.ExpressionBody", b =>
                {
                    b.HasOne("Brainvest.Dscribe.MetadataDbAccess.Entities.ExpressionDefinition", "Definition")
                        .WithMany("Bodies")
                        .HasForeignKey("DefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Brainvest.Dscribe.MetadataDbAccess.Entities.ExpressionFormat", "Format")
                        .WithMany()
                        .HasForeignKey("FormatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Brainvest.Dscribe.MetadataDbAccess.Entities.ExpressionDefinition", b =>
                {
                    b.HasOne("Brainvest.Dscribe.MetadataDbAccess.Entities.ExpressionBody", "ActiveBody")
                        .WithMany()
                        .HasForeignKey("ActiveBodyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Brainvest.Dscribe.MetadataDbAccess.Entities.AppType", "AppType")
                        .WithMany()
                        .HasForeignKey("AppTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Brainvest.Dscribe.MetadataDbAccess.Entities.EntityType", "MainInputEntityType")
                        .WithMany()
                        .HasForeignKey("MainInputEntityTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Brainvest.Dscribe.MetadataDbAccess.Entities.MetadataRelease", b =>
                {
                    b.HasOne("Brainvest.Dscribe.MetadataDbAccess.Entities.AppType", "AppType")
                        .WithMany()
                        .HasForeignKey("AppTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Brainvest.Dscribe.MetadataDbAccess.Entities.Property", b =>
                {
                    b.HasOne("Brainvest.Dscribe.MetadataDbAccess.Entities.EntityType", "DataEntityType")
                        .WithMany()
                        .HasForeignKey("DataEntityTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Brainvest.Dscribe.MetadataDbAccess.Entities.DataType", "DataType")
                        .WithMany()
                        .HasForeignKey("DataTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Brainvest.Dscribe.MetadataDbAccess.Entities.ExpressionDefinition", "ExpressionDefinition")
                        .WithMany()
                        .HasForeignKey("ExpressionDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Brainvest.Dscribe.MetadataDbAccess.Entities.Property", "ForeignKeyProperty")
                        .WithMany("Unused1")
                        .HasForeignKey("ForeignKeyPropertyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Brainvest.Dscribe.MetadataDbAccess.Entities.PropertyGeneralUsageCategory", "GeneralUsageCategory")
                        .WithMany()
                        .HasForeignKey("GeneralUsageCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Brainvest.Dscribe.MetadataDbAccess.Entities.Property", "InverseProperty")
                        .WithMany("Unused2")
                        .HasForeignKey("InversePropertyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Brainvest.Dscribe.MetadataDbAccess.Entities.EntityType", "OwnerEntityType")
                        .WithMany("Properties")
                        .HasForeignKey("OwnerEntityTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Brainvest.Dscribe.MetadataDbAccess.Entities.PropertyBehavior", b =>
                {
                    b.HasOne("Brainvest.Dscribe.MetadataDbAccess.Entities.AdditionalBehavior", "AdditionalBehavior")
                        .WithMany()
                        .HasForeignKey("AdditionalBehaviorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Brainvest.Dscribe.MetadataDbAccess.Entities.Property", "Property")
                        .WithMany("PropertyBehaviors")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Brainvest.Dscribe.MetadataDbAccess.Entities.PropertyFacetDefaultValue", b =>
                {
                    b.HasOne("Brainvest.Dscribe.MetadataDbAccess.Entities.AppInstance", "AppInstance")
                        .WithMany()
                        .HasForeignKey("AppInstanceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Brainvest.Dscribe.MetadataDbAccess.Entities.AppType", "AppType")
                        .WithMany()
                        .HasForeignKey("AppTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Brainvest.Dscribe.MetadataDbAccess.Entities.PropertyFacetDefinition", "FacetDefinition")
                        .WithMany()
                        .HasForeignKey("FacetDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Brainvest.Dscribe.MetadataDbAccess.Entities.PropertyGeneralUsageCategory", "GeneralUsageCategory")
                        .WithMany()
                        .HasForeignKey("GeneralUsageCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Brainvest.Dscribe.MetadataDbAccess.Entities.PropertyFacetDefinition", b =>
                {
                    b.HasOne("Brainvest.Dscribe.MetadataDbAccess.Entities.EnumType", "EnumType")
                        .WithMany()
                        .HasForeignKey("EnumTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Brainvest.Dscribe.MetadataDbAccess.Entities.FacetType", "FacetType")
                        .WithMany()
                        .HasForeignKey("FacetTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Brainvest.Dscribe.MetadataDbAccess.Entities.PropertyFacetValue", b =>
                {
                    b.HasOne("Brainvest.Dscribe.MetadataDbAccess.Entities.PropertyFacetDefinition", "FacetDefinition")
                        .WithMany()
                        .HasForeignKey("FacetDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Brainvest.Dscribe.MetadataDbAccess.Entities.Property", "Property")
                        .WithMany("PropertyFacetValues")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Brainvest.Dscribe.MetadataDbAccess.Entities.Reporting.ReportDefinition", b =>
                {
                    b.HasOne("Brainvest.Dscribe.MetadataDbAccess.Entities.EntityType", "EntityType")
                        .WithMany()
                        .HasForeignKey("EntityTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Brainvest.Dscribe.MetadataDbAccess.Entities.Reporting.ReportFormat", "Format")
                        .WithMany()
                        .HasForeignKey("ReportFormatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Brainvest.Dscribe.MetadataDbAccess.Entities.SavedFilter", b =>
                {
                    b.HasOne("Brainvest.Dscribe.MetadataDbAccess.Entities.EntityType", "InputEntityType")
                        .WithMany()
                        .HasForeignKey("InputEntityTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Brainvest.Dscribe.MetadataDbAccess.Entities.Security.Permission", b =>
                {
                    b.HasOne("Brainvest.Dscribe.MetadataDbAccess.Entities.EntityActionType", "ActionType")
                        .WithMany()
                        .HasForeignKey("ActionTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Brainvest.Dscribe.MetadataDbAccess.Entities.AppInstance", "AppInstance")
                        .WithMany()
                        .HasForeignKey("AppInstanceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Brainvest.Dscribe.MetadataDbAccess.Entities.EntityType", "EntityType")
                        .WithMany()
                        .HasForeignKey("EntityTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Brainvest.Dscribe.MetadataDbAccess.Entities.Security.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
