# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master
 
strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
    mac:
      imageName: 'macos-10.13'
    windows:
      imageName: 'vs2017-win2016'

pool:
  vmImage: $(imageName)

variables:
  backendDirName: 'server'
  frontDirName: 'client'

steps:
- script: 'dotnet clean $(backendDirName)/server.sln'
  displayName: Server - Clean

- script: 'dotnet build $(backendDirName)/server.sln'
  displayName: Server - Build

- script: 'dotnet test $(backendDirName)'
  displayName: Server - Test

- script: 'npm --prefix ./$(frontDirName) install'
  displayName: Client - installation

- script: 'npm run build --prefix $(frontDirName)'
  displayName: Client - Build
