# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master
 
variables:
  backendDirName: 'server'
  frontDirName: 'client'

steps:
# - task: DotNetCoreInstaller@0
#   displayName: Install .Net core 2.2
#   inputs:
#     packageType: 'sdk' # Options: runtime, sdk
#     version: '2.2.100'

- script: 'dotnet build $(backendDirName)/server.sln'
  displayName: Build

- script: 'dotnet test $(backendDirName)'
  displayName: Test

- script: 'npm install $(frontDirName)'
  displayName: Npm install
