<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>Brainvest.Dscribe.LobTools.Entities</AssemblyName>
    <RootNamespace>Brainvest.Dscribe.LobTools.Entities</RootNamespace>
  </PropertyGroup>

	<Import Project="..\..\..\SolutionInfo.xml" />

  <PropertyGroup>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <WarningsAsErrors />
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="5.0.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Abstractions\Abstractions.csproj" />
  </ItemGroup>

</Project>
