<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<UserSecretsId>aspnet-IdentityServerHost-C2CA2F30-CEF5-4399-8037-AB2C48FD5EE6</UserSecretsId>
		<LangVersion>latest</LangVersion>
		<AssemblyName>Brainvest.Dscribe.Infrastructure.SampleAuthServer</AssemblyName>
	</PropertyGroup>

	<Import Project="..\..\SolutionInfo.xml" />

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
		<WarningsAsErrors />
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
		<WarningsAsErrors />
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Duende.IdentityServer" Version="8.0.2" />
		<PackageReference Include="Duende.IdentityServer.AspNetIdentity" Version="8.0.2" />
		<PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="10.0.10" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.10" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="10.0.10" />
		<PackageReference Include="Microsoft.Build" Version="18.8.2" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.10" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.10">
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		  <PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<!--<PackageReference Include="IdentityServer4.AspNetIdentity" Version="4.1.2" />-->
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		  <PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="10.0.2" PrivateAssets="All" />
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
		<PackageReference Include="NuGet.Protocol" Version="7.6.0" />
		<PackageReference Include="MySql.EntityFrameworkCore" Version="10.0.7" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Areas\Identity\Services\" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Migrations\Migrations_Auth_PostgreSql\Migrations_Auth_PostgreSql.csproj" />
		<ProjectReference Include="..\Auth\AuthEntities\AuthEntities.csproj" />
		<ProjectReference Include="..\Helpers\Helpers.csproj" />
	</ItemGroup>

</Project>
