<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>Brainvest.Dscribe.Implementations.EfCore.BusinessDataAccess</AssemblyName>
    <RootNamespace>Brainvest.Dscribe.Implementations.EfCore.BusinessDataAccess</RootNamespace>
  </PropertyGroup>

	<Import Project="..\..\..\SolutionInfo.xml" />

	<PropertyGroup>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <WarningsAsErrors />
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="5.0.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Infrastructure\LobTools\LobTools.csproj" />
    <ProjectReference Include="..\..\..\Core\Runtime\Runtime.csproj" />
    <ProjectReference Include="..\..\..\Infrastructure\Abstractions\Abstractions.csproj" />
    <ProjectReference Include="..\..\..\Infrastructure\Helpers\Helpers.csproj" />
  </ItemGroup>

</Project>
