<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

	<Import Project="..\..\SolutionInfo.xml" />

	<ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.10" />
    <PackageReference Include="MySql.EntityFrameworkCore" Version="10.0.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Infrastructure\Auth\AuthEntities\AuthEntities.csproj" />
  </ItemGroup>

</Project>
