using System.Collections.Generic;

namespace Brainvest.Dscribe.Abstractions
{
	public interface IGlobalConfiguration
	{
		string ImplementationsDirectory { get; }
		string TempDirectory { get; }
		Dictionary<string, InstanceSettings> InstanceSettings { get; }
		InstanceSettings DefaultInstanceSettings { get; }
		InstanceSettings GetInstanceSettings(string instaneName);
		string[] ExcludeFromRequestLog { get; set; }
	}

	public class InstanceSettings
	{
		public string CopyAutoGeneratedEntitiesTo { get; set; }
		public string LoadBusinessFromAssemblyName { get; set; }
	}
}
