using System.Collections.Generic;

namespace Brainvest.Dscribe.Abstractions
{
	public interface IGlobalConfiguration
	{
		string ImplementationsDirectory { get; }
		string TempDirectory { get; }
		Dictionary<string, InstanceSettings> InstanceSettings { get; }
		InstanceSettings GetInstanceSettings(string instaneName);
	}

	public class InstanceSettings
	{
		public string CopyAutoGeneratedEntitiesTo { get; set; }
		public IEnumerable<ConnectionStringMap> ConnectionStringMaps { get; set; }
		public string LoadBusinessFromAssemblyName { get; set; }
	}

	public class ConnectionStringMap
	{
		public string From { get; set; }
		public string To { get; set; }
	}
}